debug = false

logLevel = "WARN"
defaultEntryPoints = ["https","http"]

[api]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  # uncomment the following 2 lines to redirect always to https
  #[entryPoints.http.redirect]
  #  entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  
  # Traefik will automagically create a self-signed certificate here
  # or uncomment the following lines for named individual certificates 
  #[[entryPoints.https.tls.certificates]]
  #certFile="/mnt/termine.meine-praxis.ch.crt"
  #keyFile="/mnt/termine.meine-praxis.ch.key"
  


 